default: &default
  adapter: mysql2
  # encoding: utf8
  reconnect: false
  pool: 100
  username: user
  password: ****
  host: ****

development:
  <<: *default

test:
  <<: *default
  database: fuxiong_test

production:
  <<: *default
  host: 
  database: cms
  password: ****
