default: &default
  adapter: mysql2
  # encoding: utf8
  reconnect: false
  pool: 100
  username: root
  password: slky@147
  host: zgslky.com

development:
  <<: *default
  database: Liuge@188

test:
  <<: *default
  database: fuxiong_test

production:
  <<: *default
  host: 
  database: cms
  password: slky@147