development: &default
  domain: "http://www.zgslky.com"
  mobile_domain: "http://localhost:5000"
  qiniu_bucket: "slky"
  qiniu_domain: "img.zgslky.com"
  qiniu_access_key: "xx"
  qiniu_secret_key: "xx"
  secret_key_base: xx 

test:
  <<: *default
  secret_key_base: xx

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: xx
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
